import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ModalProvider from '@/providers/ModalProvider'
import SupabaseProvider from './SupabaseProvider'
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes'
import { Toaster } from 'sonner'
import UserProvider from '@/providers/UserProvider'
import LeftSidebar from '@/components/LeftSidebar'
import RIghtSidebar from '@/components/RIghtSidebar'

export const revalidate = 0;


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} no_scroll -mt-[20px]`}>
        <Theme appearance="dark">
          <Toaster />

          <SupabaseProvider>
            <UserProvider>
              <ModalProvider />
              <div className="min-h-screen bg-gray-950 relative w-full h-full flex justify-center items-center no_scroll">
                <div className="max-w-[80%] h-full flex relative mx-auto">
                  <LeftSidebar />
                  {children}
                  <RIghtSidebar />
                </div>
              </div>
            </UserProvider>
          </SupabaseProvider>
        </Theme>

      </body>
    </html>
  )
}
