import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ModalProvider from '@/providers/ModalProvider'
import SupabaseProvider from './SupabaseProvider'
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes'
import { Toaster } from 'sonner'
import UserProvider from '@/providers/UserProvider'

export const revalidate = 0;


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} no_scroll -mt-[20px]`}>
        <Theme appearance="dark">
          <Toaster />

          <SupabaseProvider>
            <UserProvider>
              <ModalProvider />

              {children}
            </UserProvider>
          </SupabaseProvider>
        </Theme>

      </body>
    </html>
  )
}
